# Browser - Firefox on workspace 1
windowrule = workspace 1, match:class firefox

# Chat apps
windowrule = workspace 3, match:class discord
windowrule = workspace 3, match:class Slack

# Music
windowrule = workspace 5, match:class spotify

